---
- name: win_get_url module demo
  hosts: all
  become: false
  vars:
    dest: "C:\\inetpub\\wwwroot\\index.html"
    myurl: "https://releases.ansible.com/ansible/ansible-2.9.25.tar.gz"
    mydest: 'C:\\inetpub\\wwwroot\\ansible-2.9.25.tar.gz'
  tasks:
    - name: download file
      ansible.windows.win_get_url:
        url: "{{ myurl }}"
        dest: "{{ mydest }}"
